### ISSUE TITLE
JUnitOutput emits bad XML

### ISSUE THREAD

**Issue by kbuschelman** [bluebird75/luaunit#10]
There are a few minor issues.
1. CDATA section is closed incorrectly in addFailure, missing >
2. failure type attribute is closed incorrectly, missing trailing "
3. various attribute values require protection for reserved XML characters:
< and > are used in testsuite and testcase name attribute for global test functions, and
" and ' are used in certain failure type (e.g., errorMsg generated by assertEquals for a string is prettyPrinted).  For completeness, you probably want to handle & in the failure type as well since this includes error messages provided by user code.

**Comment by bluebird75** [comment]
I did some changes to the XML generated by LuaUnit, to add more information and to adhere more closely to Maven and Ant XML Schema. Would it possible for you to verify that bamboo still accept it. From the information I have about bamboo, it should be no problem.

**Comment by kbuschelman** [comment]
I'll take a look, but I won't have time for a few days.  Thanks for the update.
