### ISSUE TITLE
Respect __tostring metamethod on tables

### ISSUE THREAD

**Issue by dimo414** [bluebird75/luaunit#101]
If you define a table with a `__tostring` metamethod (common with "objects") LuaUnit will still display the "raw" table structure thanks to its (awesome!) table-tostring logic. It would be nice if LuaUnit respected tables that have defined their own tostring behavior.

Example:

```lua
t = setmetatable({function() end}, {__tostring=function() return "special table!" end})
print(t)
lu.assertNil(t)
```

Outputs:

```
special table!
lua: /tmp/luaunitdemo.lua:6: LuaUnit test FAILURE: expected: nil, actual: {function: 0x7fec63c2bff0}
```

It might make sense to add a `PRINT_TABLE_STRUCTURE_ALWAYS` (or similar) parameter similar to `PRINT_TABLE_REF_IN_ERROR_MSG` so this behavior can be configured, but I think in general the `__tostring` result will be more informative, if it exists.

I'm happy to send a PR if this makes sense. Apologies if this has already been considered, I didn't see anything in the issue history.

**Comment by bluebird75** [comment]
Hi dimo.

I have added your change request to latest luaunit since commit f44e534fd2a7a4319c3307abd27b875a3306043c . Could you verify if it meets your expectations ?

Thanks in advance.

**Comment by dimo414** [comment]
Looks great, I now see:

    stdin:1: LuaUnit test FAILURE: expected: nil, actual: special table!

which should generally be more informative. Thanks! I also wasn't aware of the `prettystr` function, good to know that exists :)

**Comment by bluebird75** [comment]
Thanks for the feedback. Out of curiosity, could you tell me in which kind of project you use LuaUnit ? And how do you feel about it, what should I remove, add or improve (besides table printing !).

**Comment by bluebird75** [comment]
If you are looking for a pretty-printer, you can also check serpent ( https://github.com/pkulchenko/serpent ). I'll evaluate switching to this in the future for LuaUnit ...

**Comment by dimo414** [comment]
I was using it to write unit tests of a small RPC application written in Lua. Nothing fancy, but tests using "objects" (meaning tables with custom `__tostring` in this context) yielded uninformative failure messages. I'll be sure to file more issues if I come across any, in the meantime thanks for making this framework! :)
