### ISSUE TITLE
Checking for errors raised as tables

### ISSUE THREAD

**Issue by MayamaTakeshi** [bluebird75/luaunit#102]
Hi, I am testing with v. 3.2.1-1

I think luaunit should be able to assert errors that are raised as tables:

> luaunit = require('luaunit')
> luaunit.assertErrorMsgEquals({id=100}, function() error({id=100}) end)
stdin:1: LuaUnit test FAILURE: Exact error message expected: {id=100}
Error message received: {id=100}

stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/luaunit.lua:608: in function 'failure'
        /usr/local/share/lua/5.1/luaunit.lua:613: in function 'fail_fmt'
        /usr/local/share/lua/5.1/luaunit.lua:796: in function 'assertErrorMsgEquals'
        stdin:1: in main chunk
        [C]: ?

I think it should work similarly to assertItemsEquals but against the raised error.

**Comment by bluebird75** [comment]
Good point. I never encountered error messages as table in the past, that's why LuaUnit does not have this functionality.

Would you be happy to code it ? I love Pull Requests :-)

**Comment by MayamaTakeshi** [comment]
Hi, sure.
I have created https://github.com/bluebird75/luaunit/pull/103
