### ISSUE TITLE
JUnit output doesn't escape class or test names

### ISSUE THREAD

**Issue by tommaisey** [bluebird75/luaunit#125]
Easy fix:

`
self.fd:write(string.format('        <testcase classname="%s" name="%s" time="%0.3f">\n',
                node.className, node.testName, node.duration ) )
`
becomes
`
self.fd:write(string.format('        <testcase classname="%s" name="%s" time="%0.3f">\n',
                 xmlEscape(node.className), xmlEscape(node.testName), node.duration ) )
`

**Comment by bluebird75** [comment]
Let me try to guess : you are using non latin1 characters in your class names ? If that's the case, indeed, this new feature of lua 3.4 was not anticipated ....

**Comment by tommaisey** [comment]
Just an occasional `&` or `<` here and there :)

**Comment by bluebird75** [comment]
How do you put such strange characters inside the class or method name ? They are not allowed inside a lua identifier.

**Comment by bluebird75** [comment]
I can not reproduce it.
