### ISSUE TITLE
assertEquals not matching some values

### ISSUE THREAD

**Issue by Sledmine** [bluebird75/luaunit#131]
Hi, I been using luaunit for a while in different projects with no problem, but now I encountered what I think it's an issue related to how assertEquals work, I'm deep comparing two arrays/tables/list of float/number values expecting them to match without problem but it looks like that for luaunit they are totally different values, this is some output:
```
Rotation array must match
expected: {0.70710678118655, 0.70710678118655, 0, 0, 0, 1}
actual: {0.70710678118655, 0.70710678118655, 0, 0, 0, 1}
List difference analysis:
* lists A (actual) and B (expected) have the same size
* lists A and B start differing at index 1
* lists A and B are equal again from index 3
* Differing parts:
  - A[1]: 0.70710678118655
  + B[1]: 0.70710678118655
  - A[2]: 0.70710678118655
  + B[2]: 0.70710678118655
* Common parts at the end of the lists
  = A[3], B[3]: 0
  = A[4], B[4]: 0
  = A[5], B[5]: 0
  = A[6], B[6]: 1
```
It seems to be related to decimal/float numbers comparation, let me know If I can help with more information, I would like to do a pull request if I found some free time.

**Comment by bluebird75** [comment]
I just added support of table to assertAlmostEquals(). You can now pass complex structures and have them compared with a margin where appropriate.

**Comment by Sledmine** [comment]
Awesome to see that, I'm pulling changes right now, thanks for the update!
