### ISSUE TITLE
assert for function returning, nil/msg?

### ISSUE THREAD

**Issue by jjvbsag** [bluebird75/luaunit#139]
Lua has a convention for functions to return nil and an error string in case of problems.
Is there an assert for this? If not, how would you implement it?

**Example:**
```lua
	local ok,msg=output:set(-2)
	assertEquals("invalid value",msg)
	assertIsNil(ok)
```
I'd prefer something like
```lua
	assertNilMsg("invalid value",output:set(-2))
```
I tried by myself with
```lua
local function assertNilMsg(want,ok,msg)
	assertEquals(want,msg)
	assertIsNil(ok)
end
```
but in error case I get the wrong line in the test results
```
Failed tests:
-------------
1) TestLuaunitNilMsg.test3
/opt/unittest/luaunit-nil-msg.lua:17: expected: "good value"
```
Line 17 is my assertNilMsg and not the test case

**Comment by bluebird75** [comment]
Hi,

It's easy to write your own assert functions. Just look on how luaunit write them. For example, here the code for assertIsNil() 👍 

```
function M.assertIsNil(value, extra_msg_or_nil)
    if value ~= nil then
        failure("expected: nil, actual: " ..prettystr(value), extra_msg_or_nil, 2)
    end
end
```

In your case, this should be something along the lines of : 

```
local function assertNilMsg(want,ok,msg)
    if ok ~= nil or want ~= msg   then
        failure("Expected: nil with msg '"..want.."', got "..prettystr(ok).." with msg '"..msg.."'", nil, 2)
    end
end
```

A few advices : it is better to always show what you expected and what you actually got in the same message. The failure() function will take care of generating the proper error.

**Comment by jjvbsag** [comment]
Thank you. You code will throw an error, is msg is nil, so I changed it to
```lua

function M.assertNilMsg(want,ok,msg)
    if ok ~= nil or want ~= msg   then
        failure("Expected: nil with msg "..prettystr(want)..", got "..prettystr(ok).." with msg "..prettystr(msg), nil, 2)
    end
end
```
But thanks for the inspiration.
Regards
