### ISSUE TITLE
Update luarocks to use last version

### ISSUE THREAD

**Issue by rodfersou** [bluebird75/luaunit#14]
Sorry, I'm new in Lua world, but luarocks is installing version 2.1, are there a way to update it?

Thanks!

**Comment by rodfersou** [comment]
Other question.. why can't I find version 2.1 at github history and tags?

**Comment by bluebird75** [comment]
Version 2.1 was forked away from my version. I am now in the process of merging everything back together (the fork and my further developments). As soon as this is done, I'll publish it on luarocks.

**Comment by rodfersou** [comment]
@bluebird75 thanks

**Comment by andreaskoepf** [comment]
+1 for making it available on luarocks

**Comment by n1tehawk** [comment]
As of commit c80efe9, an up-to-date LuaRocks version is now available.

**Comment by bluebird75** [comment]
Done after more than one year, see https://luarocks.org/modules/bluebird75/luaunit
