### ISSUE TITLE
can i search test_xxx from _ENV

### ISSUE THREAD

**Issue by shewer** [bluebird75/luaunit#147]
I want to test sub env for example as below.
thk,.
```lua
local new_env()
   local tab={}
   for k,v in ipairs({ math,package,require) do
      tab[k] = _ENV[k] 
   end
   return tab
end
local lut = require 'luaunit'
local _ENV = new_env()
-- now  test_abc in local _ENV 
function test_abc()
end
lut.run()
```

**Comment by bluebird75** [comment]
If I get it correctly, you want to create a kind of restricted environment / sandbox, where you would run your luaunit tests ?

Did you try to run it already ? The only problem I could see is how luaunit discovers tests. Normally, it discovers them from the global namespace. If that does not work, it is possible to run an explicit test function using something like:

`runSuiteByInstances( { { 'test_abc', test_abc } } )`

**Comment by shewer** [comment]
thank you a lot, The question has been resolved
