### ISSUE TITLE
bad initializer syntax in luaunit.lua:1725

### ISSUE THREAD

**Issue by n1tehawk** [bluebird75/luaunit#15]
Line #1725 of current `luaunit.lua` looks wrong to me, and actually got me an error ("variable 'fullErrMsg' is not declared").

I think the line
<code>local ok=true, fullErrMsg, stackTrace, errMsg, t</code>
should actually be
<code>local ok, fullErrMsg, stackTrace, errMsg, t = true</code>

Regards, NiteHawk

**Comment by tklink** [comment]
I confirm, this should be fixed, e.g. in the proposed way.

**Comment by n1tehawk** [comment]
If you wish to keep it more 'natural' (i.e. readable for users not that familiar with Lua), you could also split it up into two lines:

    local ok = true
    local fullErrMsg, stackTrace, errMsg, t

**Comment by bluebird75** [comment]
Thanks for the report. What bothers me is that it went unnoticed for so long...

**Comment by bluebird75** [comment]
Fixed now...
