### ISSUE TITLE
Missing locals

### ISSUE THREAD

**Issue by tklink** [bluebird75/luaunit#17]
There are several locations where "local" seems to be missing:

Line 1824: name, instance = v[1], v[2]
Line 1852: name, instance = v[1], v[2]
Line 2016: testNames = options['testNames']

Found using http://www.lua.org/extras/5.3/strict.lua

**Comment by bluebird75** [comment]
Indeed ! I've tried to fix as many as I could but those slipped through. Would you be ok to provide a pull request for this ?

Thanks a lot.

**Comment by tklink** [comment]
I have to find a way how to make pull requests. ;-)

**Comment by bluebird75** [comment]
Somebody already did. It's fixed now.
