### ISSUE TITLE
[feature request] npm/bower support

### ISSUE THREAD

**Issue by aaronmallen** [bluebird75/luaunit#19]
It would be super awesome to be able to install this into my project with `npm install` or `bower install`.  I know this isn't javascript, but I use gulp to build my libraries and being able to pull this in with a simple `npm install` would be awesome.

**Comment by AbigailBuccaneer** [comment]
This is already possible with `bower install https://github.com/bluebird75/luaunit.git`.

**Comment by bluebird75** [comment]
i verified it and it works indeed.

**Comment by aaronmallen** [comment]
Thank you @AbigailBuccaneer
