### ISSUE TITLE
`assertEquals` can't match tables with table keys

### ISSUE THREAD

**Issue by AbigailBuccaneer** [bluebird75/luaunit#30]
```Lua
> luaunit.assertEquals({ [{}] = {} }, { [{}] = {} })
```
```
stdin:1: expected: {{}={}}
actual: {{}={}}
stack traceback:
	[C]: in function 'error'
	./luaunit.lua:536: in function 'failure'
	./luaunit.lua:598: in function 'assertEquals'
	stdin:1: in main chunk
	[C]: in ?
```

**Comment by n1tehawk** [comment]
Table "equality" always is a somewhat delicate question in Lua, as tables are passed by reference. Therefore it's well possible that two tables `a` and `b` are not considered identical (i.e. Lua will report `a ~= b`), despite them both "holding" the same content.

These patches go quite some way to try and match up table-type keys (by their content) when comparing tables with `_is_table_equal()`. While that may be useful under special circumstances, I'm not convinced that I'd consider this "natural" for a *key* value comparison, or would even want it as default behavior.

Do you think this could be made optional / configurable via some `M.OPTION` setting?

Regards, NiteHawk

**Comment by n1tehawk** [comment]
>Do you think this could be made optional / configurable via some M.OPTION setting?

Turns out it's relatively easy / straightforward. See 79778d3 and d3c8008 for an example.

Regards, NiteHawk

**Comment by bluebird75** [comment]
Using table as keys is kind of evil, isn't ? At least that's why my python background (where this is forbidden, for exactly the problems it brings here) tells me.

Abigail, do you actually use code like with table as keys ?

That said, I find the proposed behavior saner : indeed, it makes sense to make the examples proposed working rather than failing.

Nitehawk, do you see a good drawback to support directly the proposed behavior instead of an option ? I prefer to make informed decisions rather than adding options.

**Comment by n1tehawk** [comment]
>That said, I find the proposed behavior saner : indeed, it makes sense to make the examples proposed working rather than failing.

As indicated above, I beg to differ. Lua itself will not consider the table keys to be equal (unless they actually _reference_ the same table). The unit tests look plausible, yes - it's just not the "natural" way of treating tables in Lua.

(Things would get even more complicated if you think of other things that you can do with tables - like assigning metatables, e.g. to make "object" use of them.)

>Nitehawk, do you see a good drawback to support directly the proposed behavior instead of an option ? I prefer to make informed decisions rather than adding options.

Admittely I won't / can't argue strongly against this - it's more a personal bias towards doing things "the Lua way" unless we have compelling reason to differ. The proposed modification is limited to table-type keys, which - as you noted - should be a unusual / rare(?) case anyway.

The single reason why I'd prefer this optional is that Lua operators `==` and `~=` will disagree with "our" evaluation of the keys. The source comment itself indicates this ("_we can have `_is_table_equals(k1, k2)` and `t[k1] ~= t[k2]`_").

How about if we find a compromise? Let's keep `M.TABLE_EQUALS_KEYBYCONTENT` and have this behavior controllable by the option, but simply default it to `true`?

Regards, NiteHawk

**Comment by n1tehawk** [comment]
Re-reading my answer made me realize that I misinterpreted that source comment - it's unrelated. What I wanted to say / emphasize is the possible `_is_table_equals(k1, k2)` vs. `k1 ~= k2` discrepancy (the latter being Lua's view of things).

**Comment by AbigailBuccaneer** [comment]
@bluebird75 It wasn't for my code - I'm a maintainer on an open source project that includes a third-party library, and the library didn't have any unit tests, and I grew distrustful of it so I started adding unit tests. (The library is for serializing Lua objects,and it explicitly states that it handles table-keyed tables.) I agree it's a silly thing to do, but I wouldn't describe it as "evil", and I'm sure at some point I've written code myself that uses tables as keys (though admittedly not in a context where you'd want to compare equality).

> The single reason why I'd prefer this optional is that Lua operators == and ~= will disagree with "our" evaluation of the keys. The source comment itself indicates this ("we can have `_is_table_equals(k1, k2)` and `t[k1] ~= t[k2]`").

The fact that Lua's `==` disagrees with `_is_table_equals` is the reason why I think comparing keys by content is correct - `t[x]` essentially finds a field `k` of `t` for which `k == x`, which means that when comparing table fields by lookup means we implicitly use `==` in our definition of `_is_table_equals` - whereas it makes more sense to me to recursively call `_is_table_equals` to check whether two keys are equal, as we do for a field's value.

That said, I can see that it may be counterintuitive. Intuitively, I'd like to have both:

```Lua
_is_table_equals(t1, t2) => _is_table_equals(t1[x], t2[x])
```
and:
```Lua
_is_table_equals(t, deep_copy(t)) -- where deep_copy is the obvious recursive routine
```

be true. But if we compare keys by content then the first one's not always true, and if we compare keys by reference equality then the second one's not always true. So I guess it does make sense to have it as an option. (I'd argue that the second code block up there is more important, as accessing fields is already known to have pitfalls when the key is a table - and so I'd still prefer it to be true.)

**Comment by n1tehawk** [comment]
@AbigailBuccaneer: What do you think of sticking with `M.TABLE_EQUALS_KEYBYCONTENT` and defaulting it to `true`? Users that insist on having "strict" table key comparisons could just edit it to `false` then...

**Comment by AbigailBuccaneer** [comment]
The longer I think about this the longer I tend towards "this is really icky and no solution will feel 'right'." - but I'd be happy for my own use-cases if it were a default-true option.

(As a fun after-thought: it'd be possible to take a table, turn it into a proxy object whose `__index` metamethod performs all lookups on that table by content. So even Lua's handling of equality in field lookup is not immutable :wink: )

**Comment by n1tehawk** [comment]
How should we proceed with this? @AbigailBuccaneer Do you intend to update your pull request? If you want to integrate my changes you could grab (or cherry-pick) from [this branch](https://github.com/n1tehawk/luaunit/commits/table-keys).

Regards, NiteHawk

**Comment by AbigailBuccaneer** [comment]
@n1tehawk Apologies, I've had almost no free time! Thanks for your changes, I've just force-pushed my branch to have the same HEAD as yours - so the pull request now also contains your changes.

Thanks again :smile:
