### ISSUE TITLE
Inconsistency across assertAlmostEqual() and assertNotAlmostEqual()

### ISSUE THREAD

**Issue by n1tehawk** [bluebird75/luaunit#33]
`assertAlmostEqual()` allows a zero margin, while `assertNotAlmostEqual()` doesn't: https://github.com/bluebird75/luaunit/blob/9c7444164d591bc6494fd35f1fc6ea830883b5be/luaunit.lua#L613 vs. https://github.com/bluebird75/luaunit/blob/9c7444164d591bc6494fd35f1fc6ea830883b5be/luaunit.lua#L649.

This is not caught by the unit test in https://github.com/bluebird75/luaunit/blob/9c7444164d591bc6494fd35f1fc6ea830883b5be/test/test_luaunit.lua#L687 as `assertError()` is rather unspecific, and we once more encounter the "error vs. failure" problem (#23). Here we're testing a 'successful' failure, while possibly expecting an actual error ("margin must be positive") instead.

I assume that we want to adjust `assertAlmostEqual()` to refute a zero margin, just like `assertNotAlmostEqual()` does, right?

Regards, NiteHawk

**Comment by bluebird75** [comment]
Actually whether allowing 0 is almostEquals cases is up to debate. If the user wants to pass 0, maybe he know what he is doing and the framework can cope with this. The fact that I am undecided showed up with two different implementations, that's bad :worried: !

What is your opinion, good idea or bad idea ?

Now, the implementation needs to be consistent for sure !

It's not the first time that an lua error is generated and misinterpreted as an expected failure. This is why I introduced later on the assertErrorMsgContains function. I was just a bit lazy by not updating all internal tests with this...

Once we have an assertFailure different from assertError, this should disappear.

**Comment by n1tehawk** [comment]
>Actually whether allowing 0 is almostEquals cases is up to debate. If the user wants to pass 0, maybe he know what he is doing and the framework can cope with this. The fact that I am undecided showed up with two different implementations, that's bad :worried: !
>
>What is your opinion, good idea or bad idea ?

I don't find it particularly useful to allow `assertAlmostEquals(a, b, 0)` - if that's what the user wants, we should encourage him to do `assertEquals(a, b)` instead?

I'm all for a consistent handling of margin for both `assertAlmostEquals` and `assertNotAlmostEquals`. This also allows factoring out common code that both functions use, see c3afd2b.

Regards, NiteHawk
