### ISSUE TITLE
[Enhancement] Rethink the pattern handling of assertErrorMsgMatches()

### ISSUE THREAD

**Issue by n1tehawk** [bluebird75/luaunit#35]
`assertErrorMsgMatches()` currently uses the `strMatch()` function to test for the expected message: https://github.com/bluebird75/luaunit/blob/fd718068b8b99079948db2662300f2f3e4d86d0c/luaunit.lua#L750. This means that the pattern in `expectedMsg` will always have to account for the _entire_ error string.

For example, when testing for a [luaL_checknumber](http://www.lua.org/manual/5.1/manual.html#luaL_checknumber) failure, it's not sufficient to have
`assertErrorMsgMatches("^bad argument.*number expected", ...)`.
You have to use
`assertErrorMsgMatches("^bad argument.*number expected.*", ...)`.
instead. (Note the `.*` padding at the end.)

I would like to suggest changing the match to a more natural `error_msg:match(expectedMsg)`, following the standard Lua pattern semantics. While this is a somewhat incompatible change over previous LuaUnit versions, it should also accept existing patterns. If a narrower / "full" match is what the user desires, it's easy enough to anchor the Lua pattern with `^` and `$` (http://www.lua.org/manual/5.1/manual.html#5.4.1).

**Comment by bluebird75** [comment]
Ok with me. 

I remember I hesitated about this. I went a bit extreem because I discovered at that time that several error within LuaUnit where mistaken as expected failures.

**Comment by n1tehawk** [comment]
I'll have to think some more about this. If we don't want to introduce another inconsistency, then `assertStrMatches` would need to be adjusted too...

**Comment by n1tehawk** [comment]
It would probably be okay to deviate from `assertStrMatches(str, pattern, start, final)`, as that already implies a parameter syntax that is different from `string.match(str, pattern, init)`. Contrary to that `assertErrorMsgMatches(pattern, ...)` can only provide one additional `pattern` argument (apart from the function invocation varargs) - so you *could* somewhat reasonably expect a "standard" `string.match(error_msg, pattern)` there.

Nevertheless I don't really like the required changes. We'd either have to rework the underlying `strMatch()` function, affecting unit tests and existing LuaUnit use cases; or we might end up with possibly different results between `assertErrorMsgMatches()` and `assertStrMatches()`, even when given an identical pattern. Neither seems to be justified by the minuscule benefit of having a slightly more flexible matching logic.

Therefore I'm closing this issue for now.
Regards, NiteHawk
