### ISSUE TITLE
Introduce ability to skip test

### ISSUE THREAD

**Issue by bluebird75** [bluebird75/luaunit#37]
Being able to skip test is a common feature of unit-tests framework.

Tyipcal usage are : 
1. within the test, discover that the test does not apply and skip it by calling skip()
2. within the test, skip the test if some condition does not apply by calling skipIf( condition )
3. mark a test function with an equivalent skipIf( ) so that the whole test function is skipped under some conditions.

For 1. and 2. the behavior of calling skip is the following : 
- test is interrupted, control is resumed to the luaunit framework
- test is reported as skipped in the final report

Case 3. is really a nice to have, but it provides a nice coding challenge. Typical usage could be 

```
skipIf( "os" = "windows", def f() ....  )
```

Report of the test suite should be adjusted in the following way : 
- if some tests are skipped in the test suite, add "x tests skipped" in the report
- if no tests are skipped, don't add anything
- do not count the number of skipped tests in the "run" ?

Example for test output

```
Ran 15 tests in 0.005 seconds, skipped 3 tests
FAILED (run=15, failures=12, skipped=3)
```

Meaning, total of 18 tests exists, 15 run, 3 skipped.

TAP output :

```
# Ran 15 tests in 0.012 seconds, 3 successes, 12 failures, 3 skipped
```

Although I am not totally sure this is the right way of reporting skipped tests. Since a test may be partially run then skipped, it's in a grey area.

For the XML reports, I remember that there is a conflict between where to report skipped tests between ANT and Jenkins. Need to verify that again.

**Comment by n1tehawk** [comment]
An unconditional `skip(fmt, ...)` (1.) and the conditional `skipIf(condition, fmt, ...)` (2.) seem nice, as they allow to control text execution from _within_ the framework (i.e. while LuaUnit is executing).
I suppose we want the ability to (optionally) pass some printf-style message.

However, I don't get what 3. is supposed to achieve? Is there some inherent benefit of using
`skipDefineIf(os_name == "windows", function f() --[[ ... ]] end)`
over
```
if os_name ~= "windows" then
    function f() --[[ ... ]] end
end
```

Regards, NiteHawk

**Comment by n1tehawk** [comment]
I have started an implementation in [this branch](https://github.com/n1tehawk/luaunit/commits/20160807_skip), by introducing a new node status `SKIPPED`. Skipped tests do not increment `passedCount` but have their own counter instead; apart from that they're treated as successful (i.e. "passing").

>For the XML reports, I remember that there is a conflict between where to report skipped tests between ANT and Jenkins. Need to verify that again.

The problem lies within the Apache Ant schema for JUnit. While Jenkins' XSD allows for a "skipped" element, Apache's schema has no concept of this. For now, I have resorted to a workaround to generate XML that will validate against both XSDs: skipped tests get reported as specialized failures with a `type="SKIPPED"` attribute - see [luaunit.lua#L1754-L1761](https://github.com/n1tehawk/luaunit/blob/5652776dde7b595ff2f217f541831195a9ccd9e0/luaunit.lua#L1754-L1761). This is probably subject to debate.

Regards, NiteHawk

**Comment by bluebird75** [comment]
The alternative is to start adding a "flavour" option to the xml we generate, which treats skipped tests differently. 

I don't like them to be visible as errors. Skip tests are simply not executed, in the worst case, we should simply not report them...

**Comment by n1tehawk** [comment]
Yes, you have a point there. In hindsight, I also noticed that [example-apache-ant.xml#L10](https://github.com/bluebird75/luaunit/blob/master/junitxml/example-apache-ant.xml#L10) has some sort of "skipped" entry - it's simply an SGML/XML comment.

We could also simply adopt the Jenkins/Hudson variant, and limit XML validation of our output to the corresponding scheme?

**Comment by bluebird75** [comment]
I collected the following source of information: Our source information:

* http://stackoverflow.com/questions/4922867/junit-xml-format-specification-that-hudson-supports
(Jenkins)
* https://github.com/jenkinsci/xunit-plugin/tree/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd
* http://help.catchsoftware.com/display/ET/JUnit+Format
* http://llg.cubic.org/docs/junit/
* https://confluence.atlassian.com/bamboo/junit-parsing-in-bamboo-289277357.html
* http://nose2.readthedocs.io/en/latest/plugins/junitxml.html
* https://pzolee.blogs.balabit.com/2012/11/jenkins-vs-junit-xml-format/
* https://www.relishapp.com/cucumber/cucumber/docs/formatters/junit-output-formatter
* http://stackoverflow.com/questions/11241781/python-unittests-in-jenkins

I need more time to analyse everything but we can certainly find a common way to report skipped tests.

**Comment by bluebird75** [comment]
was closed by mistake

**Comment by n1tehawk** [comment]
The more I thought about this, the less I liked my "failure" approach for the XML status. I've now changed that to mimic the example in _junitxml/example-apache-ant.xml_, using a comment to indicate skipped tests.

**Comment by n1tehawk** [comment]
Branch [20160807_skip](https://github.com/n1tehawk/luaunit/commits/20160807_skip) updated. Might be suitable for a pull request now...

**Comment by n1tehawk** [comment]
As for collecting resources:
* It's possible that Maven / the Surefire plugin uses yet another, incompatible XML report schema.
See http://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd or https://github.com/apache/maven-surefire/blob/master/maven-surefire-plugin/src/site/resources/xsd/surefire-test-report.xsd respectively.

**Comment by myzhan** [comment]
Hi, any progress about this feature?

Recently, I need to skip some tests under certain conditions, so I wrote sth like this.

```lua
function M.LuaUnit.applySkipIfFilter( listOfNameAndInst )
    local included, excluded = {}, {}
    for i, v in ipairs( listOfNameAndInst ) do
        local name, instance = v[1], v[2]
        if 'function' == type(instance.skipIf) then
            if instance.skipIf() then
                table.insert( excluded, v)
            else
                table.insert( included, v)
            end
        else
            table.insert( included, v)
        end
    end
    return included, excluded
end
```

And I wrote some tests like this.

```lua
TestDate = {}

function TestDate:skipIf()
    if todayIsMonday then
        -- we don't need to test on Monday
        return true
    return false
end

return TestDate
``

**Comment by bluebird75** [comment]
The feature is now implemented, I can close this pull request.

The way to skip test is to call luaunit.skip(msg) or luaunit.skipIf(condition, msg) from withing the test.

See https://github.com/bluebird75/luaunit/blob/master/test/test_luaunit.lua#L3396

**Comment by myzhan** [comment]
Cool! Am I able to skip a test suite instead of calling luaunit.skip(msg) from within every tests in the test suite?

**Comment by bluebird75** [comment]
You mean skipping a whole class ? Not directly, but you can skip in the setUp() function which in pratcice skips every test.

You need to use the master by the way, this is not released.

**Comment by myzhan** [comment]
> You mean skipping a whole class ?

Yes. So all I need to do it's calling the skip function in the setUp function. Thanks.
