### ISSUE TITLE
Preparing v3.2 release

### ISSUE THREAD

**Issue by bluebird75** [bluebird75/luaunit#44]
I am preparing a v3.2 release for soon. 
@AbigailBuccaneer  @n1tehawk if you have some pending modifications which you would like to push, now is the good time !

Cheers,

Philippe

**Comment by n1tehawk** [comment]
Hi Philippe!

I have nothing urgent on my agenda, but would like to propose two small patches. I'll create a PR for those later, after I have caught up on your latest changes (and rebased my stuff accordingly).

(Nevertheless, I do not consider either of these patches necessary or vital for the upcoming release.)

Regards, NiteHawk

**Comment by n1tehawk** [comment]
I have added two more commits: first adds a test case for `--failure`, the second addresses the TODO related to grammatical number in `statusLine()`. Feel free to cherry-pick whatever you consider useful.

Regards, NiteHawk

**Comment by n1tehawk** [comment]
I'm not sure if you still are collecting / reviewing changes for the upcoming release. If so, I have two more optional patches in my [contrib branch](https://github.com/n1tehawk/luaunit/commits/contrib) that you might consider for inclusion. (Let me know if you want me to create a PR for them.)

Regards, NiteHawk

**Comment by n1tehawk** [comment]
I think that with adding static analysis from #55 (and possibly the fixes in #56) a point will be reached where it would make sense to tag v3.2.

**Comment by bluebird75** [comment]
Sorry for the delay, real life has kept me very busy over the last few months.

The only thing really holding me back for v3.2 release is that documentaiton has not been updated to reflect the latest config for comparing recursive tables and for the --error flag.

**Comment by bluebird75** [comment]
Release done.
