### ISSUE TITLE
Can't clone repo for installation

### ISSUE THREAD

**Issue by r0fls** [bluebird75/luaunit#49]
This happens when I try to clone:

```bash
raphael@r0fls ~/Desktop/code/r0fls $ git clone git@github.com:bluebird75/luaunit.git
Cloning into 'luaunit'...
Warning: Permanently added the RSA host key for IP address '192.30.252.121' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
```
Here it works for a different repo:
```bash
Please make sure you have the correct access rights
and the repository exists.
raphael@r0fls ~/Desktop/code/r0fls $ git clone https://github.com/orangeduck/tgc.git
Cloning into 'tgc'...
remote: Counting objects: 42, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 42 (delta 14), reused 40 (delta 12), pack-reused 0
Unpacking objects: 100% (42/42), done.
Checking connectivity... done.
```
I tried using `https://` instead of `git@` for installing luaunit but it still did not work. Are the access rights correct for this repository?

**Comment by n1tehawk** [comment]
Hi r0fls!

Looks like you've tried the `git+ssh` URL first. AFAIK, that won't work unless you add a SSH key to your github profile. Use the standard HTTPS clone URL (https://github.com/bluebird75/luaunit.git) instead, it should work just fine.

Regards, NiteHawk

**Comment by r0fls** [comment]
Whoops, sorry! I thought I tried that before posting this. Thank you!
