### ISSUE TITLE
Request documentation for travis-ci/circleci integration

### ISSUE THREAD

**Issue by r0fls** [bluebird75/luaunit#51]
Would it be possible to add documentation about using luaunit with travis-ci or circleci? Or maybe it's already here somewhere...

**Comment by r0fls** [comment]
Would I just use this configuration?

https://github.com/bluebird75/luaunit/blob/master/.travis.yml

**Comment by n1tehawk** [comment]
Hi r0fls!

I don't think that your question is really related / specific to LuaUnit. LuaUnit per se is a testing framework, and doesn't deal with (or care about) continuous integration. We're making use of CI on this repository to ensure that changes the code don't break things.

What you probably want to look at is https://github.com/moteus/lua-travis-example.

Regards, NiteHawk
