### ISSUE TITLE
As a user I'd like to run nested tests

### ISSUE THREAD

**Issue by therealprof** [bluebird75/luaunit#58]
Hi guys,

I stumbled across a funny issue: I'm trying to nest testcases using multiple modules and tying them together into a test case collection by "require"ing the other modules. However there seems to be some environment-fu involved which not seem to allow me gluing my test cases together.

NB: Luaunit is not invoked by the Lua interpreter started from command line directly but by using a test driver written in C which sets up the environment via `luaL_dostring (L, "luaunit = require ('luaunit')")`, executes the testcases via `luaL_dofile (L, execfile)` and then fires of the testing using:
```
local lu = luaunit.LuaUnit.new ();
lu:setOutputType (__outputtype);
lu:setFname (__fname);
__err = lu:runSuite ()
```

All of that works fine when calling the _luaL_dofile_ on the test case directly.

But If I attempt to run the _luaL_dofile_ on something like:
```
TestFoo = require "test_foo"
TestBar = require "test_bar"
```

the testdriver will simply run zero tests without any errors. When inspecting the any of the tables returned by "require" which are supposed to contain my test functions I will get something which looks an awful lot like the table of of the luaunit module:
```
LINE_LENGTH	80
VERBOSITY_QUIET	0
assertIsString	function: 0x7fd7e8609a90
assertNotAlmostEquals	function: 0x7fd7e8609280
PRINT_TABLE_REF_IN_ERROR_MSG	false
assertIs	function: 0x7fd7e8609be0
prettystr	function: 0x7fd7e8608710
assertNotNil	function: 0x7fd7e8609910
LuaUnit	table: 0x7fd7e8608a90
VERBOSITY_LOW	1
assertEquals	function: 0x7fd7e8609940
VERBOSITY_DEFAULT	10
assertTrue	function: 0x7fd7e8609880
assertItemsEquals	function: 0x7fd7e8609c60
assertFalse	function: 0x7fd7e86098b0
assertStrIContains	function: 0x7fd7e86092f0
assertIsNumber	function: 0x7fd7e8609a30
VERSION	3.1
assertIsNil	function: 0x7fd7e8609b20
assertNotStrIContains	function: 0x7fd7e8609370
assertErrorMsgMatches	function: 0x7fd7e86099b0
assertNotEquals	function: 0x7fd7e8609240
NodeStatus	table: 0x7fd7e860afe0
assertNotIs	function: 0x7fd7e8609c20
assertIsThread	function: 0x7fd7e8609bb0
assertIsCoroutine	function: 0x7fd7e8609bb0
assertIsUserdata	function: 0x7fd7e8609b80
assertIsFunction	function: 0x7fd7e8609b50
assertErrorMsgEquals	function: 0x7fd7e8609420
USAGE	Usage: lua <your_test_suite.lua> [options] [testname1 [testname2] ... ]
Options:
  -h, --help:             Print this help
  --version:              Print version information
  -v, --verbose:          Increase verbosity
  -q, --quiet:            Set verbosity to minimum
  -o, --output OUTPUT:    Set output type to OUTPUT
                          Possible values: text, tap, junit, nil
  -n, --name NAME:        For junit only, mandatory name of xml file 
  -p, --pattern PATTERN:  Execute all test names matching the lua PATTERN
                          May be repeated to include severals patterns
                          Make sure you esape magic chars like +? with %
  testname1, testname2, ... : tests to run in the form of testFunction, 
                              TestClass or TestClass.testMethod

assertStrMatches	function: 0x7fd7e86093b0
assertNotStrContains	function: 0x7fd7e8609330
assertStrContains	function: 0x7fd7e86092b0
assertErrorMsgContains	function: 0x7fd7e8609450
assertIsTable	function: 0x7fd7e8609ac0
assertAlmostEquals	function: 0x7fd7e8609210
assertError	function: 0x7fd7e8609850
assertIsBoolean	function: 0x7fd7e8609af0
VERBOSITY_VERBOSE	20
assertNil	function: 0x7fd7e86098e0
ORDER_ACTUAL_EXPECTED	true
private	table: 0x7fd7e8607e70
```

Any ideas how to get this done?

**Comment by n1tehawk** [comment]
Hello therealprof!

Your basic approach seems fine - as long as you would get `TestFoo` and `TestBar` set correctly. The one thing to remember is that running LuaUnit by default will collect test(suite)s from the global environment, picking up anything that starts with "[Tt]est", see [luaunit.lua#L1451-L1469](https://github.com/bluebird75/luaunit/blob/d7a09f0f3dca4755959796c6f106f4f38e41b857/luaunit.lua#L1451-L1469). These entities should be either plain **functions** or **"classes"** (tables of functions).

>When inspecting any of the tables returned by "require" which are supposed to contain my test functions I will get something which looks an awful lot like the table of of the luaunit module: [...]

That doesn't seem right, and may well be the cause of your problems. Make sure that your test modules return the expected types (for example you could print or return `luaunit.prettystr(TestFoo)` for inspecton).

For example, this is how `test_bar.lua` could look like:
```lua
local lu = require("luaunit")

local function TestCaseBar()
    lu.assertIsString("bar")
end

return TestCaseBar
```
or a test "class" in `test_foo.bar`:
```lua
local lu = require("luaunit")

local TestCaseFoo = {}

function TestCaseFoo.test1()
    lu.assertIsString("foo")
end

function TestCaseFoo.test2()
    lu.assertNotEquals("foo", "bar")
end

return TestCaseFoo
```
With that, your code should run well. Note that you could make use of the predefined _LuaUnit_ instance ("runner") to keep things simple - and you probably should `return` the result if you want to query it from the C side:
```lua
TestFoo = require "foo"
TestBar = require "bar"

local lu = require("luaunit")
return lu.LuaUnit.run("--output", "text")
```
This allows you to easily add more options, or e.g. run specific (sets of) tests, like `lu.LuaUnit.run("--output", "text", "--verbose", "TestFoo")`.

If you are not concerned with "polluting" the global namespace (= environment), then you might just as well have the test modules define global vars directly, and 'include' them via `dofile`. E.g. put this into `test_foobar.lua`:
```lua
local lu = require("luaunit")

function TestFoobar()
    lu.assertIsString("foobar")
end
```
Now you can add this test (function) by doing `dofile "test_foobar.lua"` in your main Lua code.

Regards, NiteHawk

**Comment by therealprof** [comment]
Thanks for your swift reply. Unfortunately even the example you gave does not work. Here's what I tried based on your suggestions.

File test_foo.lua:
```
local lu = require("luaunit")

local TestCaseFoo = {}

function TestCaseFoo.test1()
        lu.assertIsString("foo")
end

function TestCaseFoo.test2()
        lu.assertNotEquals("foo", "bar")
end

return TestCaseFoo
```

file test.lua:
```
TestFoo = require "test_foo"

local lu = require("luaunit")
return lu.LuaUnit.run("--output", "text")
```

Execution result:

> lua ./test.lua
> 
> Ran 0 tests in 0.000 seconds
> OK

**Comment by n1tehawk** [comment]
What version of LuaUnit are you using? It that the current one from the github "master" branch (https://github.com/bluebird75/luaunit/raw/master/luaunit.lua), or an older one e.g. installed via LuaRocks?

Doing the very same from your example results in
>..
>Ran 2 tests in 0.000 seconds, 2 successes, 0 failures
>OK

for me...

**Comment by therealprof** [comment]
I'm using the 3.1 release tarball.

**Comment by n1tehawk** [comment]
I see. _LuaUnit_ has received quite a few changes since then. Since it's basically is a single Lua file, could you retry it with the up-to-date version from the URL above?

**Comment by therealprof** [comment]
Doesn't work either (just downloaded the linked file with wget, hence the suffix .1):

> LUA_PATH=../luaunit/luaunit.lua.1  lua ./test.lua
> 
> Ran 0 tests in 0.000 seconds, 0 successes, 0 failures
> OK

Just to make sure that the desired luaunit is used, here's without the LUA_PATH:

> lua ./test.lua
> lua: ./test_foo.lua:1: module 'luaunit' not found:
> 	no field package.preload['luaunit']
> 	no file '/usr/local/share/lua/5.2/luaunit.lua'
> 	no file '/usr/local/share/lua/5.2/luaunit/init.lua'
> 	no file '/usr/local/lib/lua/5.2/luaunit.lua'
> 	no file '/usr/local/lib/lua/5.2/luaunit/init.lua'
> 	no file './luaunit.lua'
> 	no file '/usr/local/lib/lua/5.2/luaunit.so'
> 	no file '/usr/local/lib/lua/5.2/loadall.so'
> 	no file './luaunit.so'
> stack traceback:
> 	[C]: in function 'require'
> 	./test_foo.lua:1: in main chunk
> 	[C]: in function 'require'
> 	./test.lua:1: in main chunk
> 	[C]: in ?

**Comment by n1tehawk** [comment]
That's weird... :confused: 
>luaunit # lua-5.2 -v realprof.lua
>Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
>..
>Ran 2 tests in 0.000 seconds
>OK

Please change `test.lua` to
```lua
TestFoo = require "test_foo"

local lu = require("luaunit")
print(lu.prettystr(TestFoo))
lu.assertIsTable(TestFoo)
lu.assertIsTable(_G.TestFoo)
return lu.LuaUnit.run("--output", "text")
```

The expected output (tested with Lua 5.2.4) is something like
```
{test1=function: 0x9016f38, test2=function: 0x9016f80}
..
Ran 2 tests in 0.000 seconds, 2 successes, 0 failures
OK
```

**Comment by therealprof** [comment]
> LUA_PATH=../luaunit/luaunit.lua.1  lua ./test.lua
> {
>     FAILURE_PREFIX="LuaUnit test FAILURE: ",
>     LINE_LENGTH=80,
>     LuaUnit={
>         __class__="LuaUnit",
>         addStatus=function: 0x7fdf7a42c5d0,
>         applyPatternFilter=function: 0x7fdf7a42cea0,
>         asFunction=function: 0x7fdf7a42c370,
>         collectTests=function: 0x7fdf7a42c3a0,
>         endClass=function: 0x7fdf7a427ef0,
>         endSuite=function: 0x7fdf7a42c630,
>         endTest=function: 0x7fdf7a42c600,
>         execOneFunction=function: 0x7fdf7a42c7f0,
>         expandClasses=function: 0x7fdf7a42ce60,
>         expandOneClass=function: 0x7fdf7a42ce20,
>         help=function: 0x7fdf7a42c400,
>         isClassMethod=function: 0x7fdf7a42c4e0,
>         isMethodTestName=function: 0x7fdf7a42c540,
>         isTestName=function: 0x7fdf7a42c570,
>         new=function: 0x7fdf7a42b2b0,
>         outputType={
>             __class__="TextOutput",
>             displayFailedTests=function: 0x7fdf7a42c050,
>             displayOneFailedTest=function: 0x7fdf7a42be60,
>             endSuite=function: 0x7fdf7a42c080,
>             endTest=function: 0x7fdf7a42bee0,
>             new=function: 0x7fdf7a42bdf0,
>             startSuite=function: 0x7fdf7a42bd50,
>             startTest=function: 0x7fdf7a42beb0
>         },
>         parseCmdLine=function: 0x7fdf7a42c3d0,
>         patternInclude=function: 0x7fdf7a42c460,
>         protectedCall=function: 0x7fdf7a42c740,
>         run=function: 0x7fdf7a42cf40,
>         runSuite=function: 0x7fdf7a42cf70,
>         runSuiteByInstances=function: 0x7fdf7a42ced0,
>         runSuiteByNames=function: 0x7fdf7a42cf10,
>         setOutputType=function: 0x7fdf7a42c660,
>         splitClassMethod=function: 0x7fdf7a42c510,
>         startClass=function: 0x7fdf7a42c8f0,
>         startSuite=function: 0x7fdf7a42cdc0,
>         startTest=function: 0x7fdf7a42c5a0,
>         statusLine=function: 0x7fdf7a42cd60,
>         verbosity=10,
>         version=function: 0x7fdf7a42c430
>     },
>     NodeStatus={
>         ERROR="ERROR",
>         FAIL="FAIL",
>         PASS="PASS",
>         __class__="NodeStatus",
>         error=function: 0x7fdf7a42b770,
>         fail=function: 0x7fdf7a42bb20,
>         isError=function: 0x7fdf7a42c9a0,
>         isFailure=function: 0x7fdf7a42c970,
>         isNotPassed=function: 0x7fdf7a42c940,
>         isPassed=function: 0x7fdf7a42c8c0,
>         new=function: 0x7fdf7a42c820,
>         pass=function: 0x7fdf7a42be90,
>         statusXML=function: 0x7fdf7a42c9d0
>     },
>     ORDER_ACTUAL_EXPECTED=true,
>     PRINT_TABLE_REF_IN_ERROR_MSG=false,
>     Run=function: 0x7fdf7a42cf40,
>     SetVerbosity=function: 0x7fdf7a42cfe0,
>     TABLE_EQUALS_KEYBYCONTENT=true,
>     USAGE="Usage: lua <your_test_suite.lua> [options] [testname1 [testname2] ... ]\nOptions:\n  -h, --help:             Print this help\n  --version:              Print version information\n  -v, --verbose:          Increase verbosity\n  -q, --quiet:            Set verbosity to minimum\n  -e, --error:            Stop on first error\n  -f, --failure:          Stop on first failure or error\n  -o, --output OUTPUT:    Set output type to OUTPUT\n                          Possible values: text, tap, junit, nil\n  -n, --name NAME:        For junit only, mandatory name of xml file\n  -p, --pattern PATTERN:  Execute all test names matching the Lua PATTERN\n                          May be repeated to include severals patterns\n                          Make sure you escape magic chars like +? with %\n  testname1, testname2, ... : tests to run in the form of testFunction,\n                              TestClass or TestClass.testMethod\n",
>     VERBOSITY_DEFAULT=10,
>     VERBOSITY_LOW=1,
>     VERBOSITY_QUIET=0,
>     VERBOSITY_VERBOSE=20,
>     VERSION="3.2",
>     WrapFunctions=function: 0x7fdf7a4293c0,
>     almostEquals=function: 0x7fdf7a427bb0,
>     assertAlmostEquals=function: 0x7fdf7a427c50,
>     assertBoolean=function: 0x7fdf7a428c80,
>     assertCoroutine=function: 0x7fdf7a428ea0,
>     assertEquals=function: 0x7fdf7a427b40,
>     assertError=function: 0x7fdf7a4287a0,
>     assertErrorMsgContains=function: 0x7fdf7a4289a0,
>     assertErrorMsgEquals=function: 0x7fdf7a428960,
>     assertErrorMsgMatches=function: 0x7fdf7a4289f0,
>     assertFalse=function: 0x7fdf7a428800,
>     assertFunction=function: 0x7fdf7a428d20,
>     assertIs=function: 0x7fdf7a4292d0,
>     assertIsBoolean=function: 0x7fdf7a428c80,
>     assertIsCoroutine=function: 0x7fdf7a428ea0,
>     assertIsFunction=function: 0x7fdf7a428d20,
>     assertIsNil=function: 0x7fdf7a428830,
>     assertIsNumber=function: 0x7fdf7a428af0,
>     assertIsString=function: 0x7fdf7a428b60,
>     assertIsTable=function: 0x7fdf7a428bf0,
>     assertIsThread=function: 0x7fdf7a428ea0,
>     assertIsUserdata=function: 0x7fdf7a428df0,
>     assertItemsEquals=function: 0x7fdf7a429350,
>     assertNil=function: 0x7fdf7a428830,
>     assertNotAlmostEquals=function: 0x7fdf7a427cf0,
>     assertNotBoolean=function: 0x7fdf7a429110,
>     assertNotCoroutine=function: 0x7fdf7a429260,
>     assertNotEquals=function: 0x7fdf7a427cb0,
>     assertNotFunction=function: 0x7fdf7a429180,
>     assertNotIs=function: 0x7fdf7a429310,
>     assertNotIsBoolean=function: 0x7fdf7a429110,
>     assertNotIsCoroutine=function: 0x7fdf7a429260,
>     assertNotIsFunction=function: 0x7fdf7a429180,
>     assertNotIsNil=function: 0x7fdf7a427b10,
>     assertNotIsNumber=function: 0x7fdf7a428fc0,
>     assertNotIsString=function: 0x7fdf7a429030,
>     assertNotIsTable=function: 0x7fdf7a4290a0,
>     assertNotIsThread=function: 0x7fdf7a429260,
>     assertNotIsUserdata=function: 0x7fdf7a4291f0,
>     assertNotNil=function: 0x7fdf7a427b10,
>     assertNotNumber=function: 0x7fdf7a428fc0,
>     assertNotStrContains=function: 0x7fdf7a4288a0,
>     assertNotStrIContains=function: 0x7fdf7a4288e0,
>     assertNotString=function: 0x7fdf7a429030,
>     assertNotTable=function: 0x7fdf7a4290a0,
>     assertNotThread=function: 0x7fdf7a429260,
>     assertNotUserdata=function: 0x7fdf7a4291f0,
>     assertNumber=function: 0x7fdf7a428af0,
>     assertStrContains=function: 0x7fdf7a427d20,
>     assertStrIContains=function: 0x7fdf7a428860,
>     assertStrMatches=function: 0x7fdf7a428920,
>     assertString=function: 0x7fdf7a428b60,
>     assertTable=function: 0x7fdf7a428bf0,
>     assertThread=function: 0x7fdf7a428ea0,
>     assertTrue=function: 0x7fdf7a4287d0,
>     assertUserdata=function: 0x7fdf7a428df0,
>     assert_almost_equals=function: 0x7fdf7a427c50,
>     assert_boolean=function: 0x7fdf7a428c80,
>     assert_coroutine=function: 0x7fdf7a428ea0,
>     assert_equals=function: 0x7fdf7a427b40,
>     assert_error=function: 0x7fdf7a4287a0,
>     assert_error_msg_contains=function: 0x7fdf7a4289a0,
>     assert_error_msg_equals=function: 0x7fdf7a428960,
>     assert_error_msg_matches=function: 0x7fdf7a4289f0,
>     assert_false=function: 0x7fdf7a428800,
>     assert_function=function: 0x7fdf7a428d20,
>     assert_is=function: 0x7fdf7a4292d0,
>     assert_is_boolean=function: 0x7fdf7a428c80,
>     assert_is_coroutine=function: 0x7fdf7a428ea0,
>     assert_is_function=function: 0x7fdf7a428d20,
>     assert_is_nil=function: 0x7fdf7a428830,
>     assert_is_number=function: 0x7fdf7a428af0,
>     assert_is_string=function: 0x7fdf7a428b60,
>     assert_is_table=function: 0x7fdf7a428bf0,
>     assert_is_thread=function: 0x7fdf7a428ea0,
>     assert_is_userdata=function: 0x7fdf7a428df0,
>     assert_items_equals=function: 0x7fdf7a429350,
>     assert_nil=function: 0x7fdf7a428830,
>     assert_not_almost_equals=function: 0x7fdf7a427cf0,
>     assert_not_boolean=function: 0x7fdf7a429110,
>     assert_not_coroutine=function: 0x7fdf7a429260,
>     assert_not_equals=function: 0x7fdf7a427cb0,
>     assert_not_function=function: 0x7fdf7a429180,
>     assert_not_is=function: 0x7fdf7a429310,
>     assert_not_is_boolean=function: 0x7fdf7a429110,
>     assert_not_is_coroutine=function: 0x7fdf7a429260,
>     assert_not_is_function=function: 0x7fdf7a429180,
>     assert_not_is_nil=function: 0x7fdf7a427b10,
>     assert_not_is_number=function: 0x7fdf7a428fc0,
>     assert_not_is_string=function: 0x7fdf7a429030,
>     assert_not_is_table=function: 0x7fdf7a4290a0,
>     assert_not_is_thread=function: 0x7fdf7a429260,
>     assert_not_is_userdata=function: 0x7fdf7a4291f0,
>     assert_not_nil=function: 0x7fdf7a427b10,
>     assert_not_number=function: 0x7fdf7a428fc0,
>     assert_not_str_contains=function: 0x7fdf7a4288a0,
>     assert_not_str_icontains=function: 0x7fdf7a4288e0,
>     assert_not_string=function: 0x7fdf7a429030,
>     assert_not_table=function: 0x7fdf7a4290a0,
>     assert_not_thread=function: 0x7fdf7a429260,
>     assert_not_userdata=function: 0x7fdf7a4291f0,
>     assert_number=function: 0x7fdf7a428af0,
>     assert_str_contains=function: 0x7fdf7a427d20,
>     assert_str_icontains=function: 0x7fdf7a428860,
>     assert_str_matches=function: 0x7fdf7a428920,
>     assert_string=function: 0x7fdf7a428b60,
>     assert_table=function: 0x7fdf7a428bf0,
>     assert_thread=function: 0x7fdf7a428ea0,
>     assert_true=function: 0x7fdf7a4287d0,
>     assert_userdata=function: 0x7fdf7a428df0,
>     genericOutput={
>         __class__="genericOutput",
>         addStatus=function: 0x7fdf7a42b1f0,
>         endClass=function: 0x7fdf7a427eb0,
>         endSuite=function: 0x7fdf7a427ed0,
>         endTest=function: 0x7fdf7a42b210,
>         new=function: 0x7fdf7a42b190,
>         startClass=function: 0x7fdf7a42b0f0,
>         startSuite=function: 0x7fdf7a427e70,
>         startTest=function: 0x7fdf7a427e90
>     },
>     prettystr=function: 0x7fdf7a428000,
>     private={
>         __genSortedIndex=function: 0x7fdf7a4038b0,
>         _is_table_equals=function: 0x7fdf7a428600,
>         _table_keytostring=function: 0x7fdf7a428420,
>         _table_tostring=function: 0x7fdf7a428450,
>         fail_fmt=function: 0x7fdf7a4286a0,
>         hasNewLine=function: 0x7fdf7a427f10,
>         prefixString=function: 0x7fdf7a427f40,
>         prettystrPadded=function: 0x7fdf7a428060,
>         sortedPairs=function: 0x7fdf7a427d90,
>         strMatch=function: 0x7fdf7a427e20,
>         stripLuaunitTrace=function: 0x7fdf7a428140,
>         strsplit=function: 0x7fdf7a403910,
>         xmlCDataEscape=function: 0x7fdf7a428110,
>         xmlEscape=function: 0x7fdf7a4280e0
>     },
>     run=function: 0x7fdf7a42cf40,
>     setVerbosity=function: 0x7fdf7a42cfe0,
>     set_verbosity=function: 0x7fdf7a42cfe0,
>     wrapFunctions=function: 0x7fdf7a4293c0,
>     wrap_functions=function: 0x7fdf7a4293c0
> }
> 
> Ran 0 tests in 0.000 seconds, 0 successes, 0 failures
> OK
>

**Comment by n1tehawk** [comment]
WTF? You're again getting the _LuaUnit_ (module) table back in `TestFoo`, which is definitely **not** supposed to happen. Are you sure you're including the right _test_foo.lua_ file via `require`?

**Comment by therealprof** [comment]
Yes, those files we're just created for the purpose of this experiment and are not related in any form or shape to the real files.

Hah, I found the culprit, it's the LUA_PATH thing! For the sake of figuring this out I created I dir just for this test and put luaunit.lua directly in it, next to the testcases:

> $ ls
> luaunit.lua  test.lua  test_foo.lua

Now if I run with LUA_PATH set, it's all messed up:

> $ LUA_PATH=luaunit.lua lua test.lua 
> 
> Ran 0 tests in 0.000 seconds, 0 successes, 0 failures
> OK

Without it works just fine:

> $ lua test.lua 
> ..
> Ran 2 tests in 0.000 seconds, 2 successes, 0 failures
> OK

**Comment by n1tehawk** [comment]
Be careful with `LUA_PATH` and/or `package.path`. Setting it to "luaunit.lua lua test.lua" is plain wrong - see e.g. https://www.lua.org/pil/8.1.html.

**Comment by therealprof** [comment]
Why is that wrong? According to that page this is perfectly valid...

> A component does not need to have interrogation marks; it can be a fixed file name, such as the last component in the following path:
> 
>     ?;?.lua;/usr/local/default.lua
> In this case, whenever require cannot find another option, it will run this fixed file. (Of course, it only makes sense to have a fixed component as the last component in a path.) Before require runs a chunk, it defines a global variable _REQUIREDNAME containing the virtual name of the file being required. We can use these facilities to extend the functionality of require. In an extreme example, we may set the path to something like "/usr/local/lua/newrequire.lua", so that every call to require runs newrequire.lua, which can then use the value of _REQUIREDNAME to actually load the required file.

**Comment by n1tehawk** [comment]
>Why is that wrong? According to that page this is perfectly valid...

It's valid, but certainly not what you mean / want! Your LUA_PATH **starts** with the fixed filename `luaunit.lua`. Guess what `TestFoo = require "test_foo"` will result in?

**Comment by therealprof** [comment]
I see, this explains it. Thanks for bearing with me.
