### ISSUE TITLE
Run tests in random order

### ISSUE THREAD

**Issue by bluebird75** [bluebird75/luaunit#60]
It's a nice feature which I have seen in other test frameworks : provide a command line option to run tests in a random order. This increases the chances of finding some inter-test dependency issues.

Proposal : 
* -r / --random command line option
* TestClass order are randomized
* tests within a testclass are randomized

Task is up for adoption

**Comment by n1tehawk** [comment]
This was (mostly) addressed by merging #73.

**Comment by bluebird75** [comment]
Indeed.
