### ISSUE TITLE
run luaunit on MacOs X 

### ISSUE THREAD

**Issue by bluebird75** [bluebird75/luaunit#70]
Hey, while we are at having fun with Travis CI, why not take advantage of their MacOs support ?

I don't think it brings any new stuff to luaunit, as it is a pure lua module, platform independant by design but I find the idea of covering the 3 major platform pleasant. 

Goal : add MacOs build to travis-ci for luaunit.

**Comment by n1tehawk** [comment]
Add [some lines](https://github.com/n1tehawk/luaunit/commit/f89ca020fd903b989ddd13a5a03798b01993d7bd) to `.travis.yml`, and you're [good to go](https://travis-ci.org/n1tehawk/luaunit/builds/148239346). :grinning:

But as you've noted: Besides "marketing", there's little point in doing so. _LuaUnit_ is a single Lua file, and as such it should be platform-agnostic. We don't expect any nasty surprises here...

**Comment by bluebird75** [comment]
And that's it, it works by default ? That's too easy isn't it ?

**Comment by n1tehawk** [comment]
Yes, highly suspicious... :wink:

I don't really mind if this is added to the build matrix, it just seems a bit futile to me. I suggest we keep this in mind until someone reports an actual problem / a regression with Mac OS X - which then must have something to do with the Lua implementation in question, or e.g. the way that the OS runs our test suite.

**Comment by n1tehawk** [comment]
I like your idea of adding Mac OS X, but restricting it to a single configuration to limit the impact on the Travis build matrix. It looks like you've been struggling a bit with that - #74 should solve it.

**Comment by bluebird75** [comment]
issue implemented in 98a91f849c079deccc1f108cdef5dd0110e4e6f2
