### ISSUE TITLE
luaunit equivalent of pytest "pass"

### ISSUE THREAD

**Issue by nosteine** [bluebird75/luaunit#84]
In luaunit test, I would like to force the test to pass if an assert do not cause an error.
For example if i am testing an error case like this:
'assert(msg == expected_error)'
If the test asserts here, fine - there error message is correct.
If not, I would like to force the test to pass and not continue to other lines of code.

Thanks in advance

**Comment by n1tehawk** [comment]
You might have a look at #37 - if I understand you correctly then
`skipIf(msg == expected_error, "Got expected message")`
would cover your use case? (It skips the remainder of the test function in question, while being considered 'successful'.)

Regards, NiteHawk

**Comment by bluebird75** [comment]
Today, you can do that just with a return. A test which does not generate an error is considered as passed. We will consider adding an explicit marker for this.

@n1tehawk , test skipping is slightly different. When you skip a test, it is reported as not run and therefore neither passed or failed.

**Comment by nosteine** [comment]
Thanks @n1tehawk  and @bluebird75 
Turns out what I really needed is to properly use assertErrorMsgEquals ...
