### ISSUE TITLE
Unit test discovery

### ISSUE THREAD

**Issue by adrianherrera** [bluebird75/luaunit#99]
Hi there,

Does luaunit have an equivalent to Python's test discovery functionality, as described [here](https://docs.python.org/2/library/unittest.html#test-discovery)?

Currently I have a "runner" file that must list the individual tests (see [here](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/spec/lua/run_test_suite.lua)), and I want to avoid this.

Sorry, I'm a bit of a Lua newb!

Thanks,
Adrian

**Comment by bluebird75** [comment]
No, luaunit does not have this, but it's something I want to add in a distant future.

You may consider other lua unit-test frameworks who have this, like [busted](https://olivinelabs.com/busted/).

**Comment by adrianherrera** [comment]
Cool, thanks for the response! I hadn't come across busted before
